MvcApplication/Controllers/CotizacionController.cs
using AplicationCore.Services;
using Infraestructure.Models;
using iText.IO.Font.Constants;
using iText.IO.Image;
using iText.Kernel.Colors;
using iText.Kernel.Font;
using iText.Kernel.Geom;
using iText.Kernel.Pdf;
using iText.Kernel.Pdf.Canvas.Draw;
using iText.Layout;
using iText.Layout.Borders;
using iText.Layout.Element;
using iText.Layout.Properties;
using MvcApplication.Util;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Security;

using Web.ViewModel;

namespace MvcApplication.Controllers
{
    public class CotizacionController : Controller
    {
        // GET: Cotizacion
        public ActionResult Index()
        {
            //IEnumerable<Articulo> lista = null;
            try
            {
                IServiceArticulo _ServiceArticulo = new ServiceArticulo();
                ViewBag.listaArticulos = _ServiceArticulo.GetArticulo();
                if (TempData["mensaje"] != null)
                    ViewBag.NotificationMessage = TempData["mensaje"].ToString();

            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
            }
            ViewBag.DetalleIngreso = Cotizacion.Instancia.Items;
            return View();
        }

        public ActionResult Cotizar(int? id)
        {

            int cantidadCompra = Cotizacion.Instancia.Items.Count();
            ViewBag.NotificationMessage = Cotizacion.Instancia.AgregarItem((int)id);
            TempData["mensaje"] = Util.SweetAlertHelper.Mensaje("Cotización", "Artículo agregado a la orden", SweetAlertMessageType.success);
            return RedirectToAction("Index");

        }

        public ActionResult actualizarCantidad(int idArticulo, int cantidad)
        {
            ViewBag.DetalleOrden = Cotizacion.Instancia.Items;
            TempData["NotiCarrito"] = Cotizacion.Instancia.SetItemCantidad(idArticulo, cantidad);
            TempData.Keep();
            return PartialView("_PartialViewDetalle", Cotizacion.Instancia.Items);

        }

        //POR AQUI PUEDE ANDAR EL ERROR DE QUE SE ESCONDE EL CARRITO 
        public ActionResult actualizarOrdenCantidad()
        {
            if (TempData.ContainsKey("NotiCarrito"))
            {
                ViewBag.NotiCarrito = TempData["NotiCarrito"];
            }
            int cantidadLibros = Carrito.Instancia.Items.Count();
            return PartialView("_PartialViewDetalle");

        }

        public ActionResult eliminarProducto(long? id)
        {
            try
            {
                TempData["mensaje"] = Cotizacion.Instancia.EliminarItem((long)id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
            }
            return RedirectToAction("Index");
        }

        public ActionResult buscarArticuloxNombre(string filtro)
        {
            IEnumerable<Articulo> lista = null;
            IServiceArticulo _ServiceArticulo = new ServiceArticulo();

            // Error porque viene en blanco 
            if (string.IsNullOrEmpty(filtro))
            {
                lista = _ServiceArticulo.GetArticulo();
            }
            else
            {
                lista = _ServiceArticulo.GetArticuloByNombre(filtro);
            }


            // Retorna un Partial View
            return PartialView("_PartialViewVistaxNombre", lista);
        }

        public JsonResult ActualizarCheckBoxCotizacion(bool isChecked)
        {
            //Actualiza la variable de sesión con el estado actual del CheckBox
            Session["Cotizar"] = isChecked;

            //Devuelve el nuevo estado del CheckBox al cliente
            return Json(isChecked, JsonRequestBehavior.AllowGet);
        }

        public static string emailCotizacion { get; set; }

        public ActionResult EnviarCorreo(Venta venta)
        {
            //Obtiene los datos del formulario y los guarda en variables
            emailCotizacion = Request.Form["emailCotizar"];

            //Actualiza la variable de sesión con el resultado del formulario
            Session["Cotizar"] = true;

            IServiceUsuario serviceUsuario = new ServiceUsuario();
            try
            {
                if (Cotizacion.Instancia.Items.Count() <= 0)
                {
                    return RedirectToAction("");
                }
                else
                {
                    Facturas factura = new Facturas();
                    Usuario user = serviceUsuario.GetUsuarioByID(Convert.ToInt32(TempData["idUser"]));

                    //Aqui hay que validar que no vengan cosas vacias
                    if (emailCotizacion != null)
                    {
                        IServiceArticulo serviceArticulo = new ServiceArticulo();

                        Articulo articulo = new Articulo();
                        var listaLinea = Cotizacion.Instancia.Items;

                        string descuento2 = "";
                        int contador = 0;

                        foreach (var items in listaLinea)
                        {
                            Detalle_Venta linea = new Detalle_Venta();


                            contador++;

                            linea.articulo_id = (int)items.idArticulo;
                            linea.cantidad = items.cantidad;
                            venta.impuesto = (double?)Carrito.Instancia.GetImpuesto();
                            venta.usuario_id = Convert.ToInt32(TempData["idUser"]);
                            venta.estado = true;
                            linea.venta_id = venta.id;
                            linea.precio = items.precio;
                            venta.fecha = System.DateTime.Now;
                            linea.descuento = 0;
                            venta.monto_total = (double?)Carrito.Instancia.GetTotal();
                            venta.Detalle_Venta.Add(linea);

                            descuento2 = Convert.ToString(linea.descuento);
                        }
                        TempData["mensaje"] = Util.SweetAlertHelper.Mensaje("Cotización exitosa", "Una nueva cotización ha sido registrada", SweetAlertMessageType.success);

                        //FACTURA
                        factura.venta_id = venta.id;
                        factura.empresa_id = 1;

                        IServiceFactura serviceFactura = new ServiceFactura();


                        //------------------------------------------------------------------------------------------------------------------------
                        //Crear el pdf de la factura--------------------------------------------------------------------------------------
                        //------------------------------------------------------------------------------------------------------------------------
                        MemoryStream ms = new MemoryStream();
                        FileContentResult FileFact = null;
                        try
                        {

                            PdfWriter writer = new PdfWriter(ms);
                            PdfDocument pdfDoc = new PdfDocument(writer);
                            Document doc = new Document(pdfDoc, PageSize.A4, false);


                            // Fuente personalizada para el número de artículo
                            PdfFont numeroArticuloFont = PdfFontFactory.CreateFont(StandardFonts.HELVETICA_BOLD);

                            // Fuente personalizada para la descripción del artículo
                            PdfFont descripcionFont = PdfFontFactory.CreateFont(StandardFonts.HELVETICA);

                            // Fuente personalizada para la cantidad y el precio unitario
                            PdfFont cantidadPrecioFont = PdfFontFactory.CreateFont(StandardFonts.HELVETICA_OBLIQUE);

                            // Fuente personalizada para el subtotal, impuesto y total
                            PdfFont totalFont = PdfFontFactory.CreateFont(StandardFonts.HELVETICA_BOLDOBLIQUE);

                            // Encabezado
                            Paragraph header = new Paragraph("Cotización de productos")
                                .SetFont(PdfFontFactory.CreateFont(StandardFonts.HELVETICA_BOLD))
                                .SetFontSize(18)
                                .SetTextAlignment(TextAlignment.CENTER); // Alinea el contenido al centro
                            doc.Add(header);

                            // Logo y atendido por
                            Image logo = new Image(ImageDataFactory.Create("C:/logo1.png", false))
                                .SetHeight(50)
                                .SetWidth(120)
                                .SetHorizontalAlignment(HorizontalAlignment.CENTER)
                                .SetFont(PdfFontFactory.CreateFont(StandardFonts.HELVETICA))
                                .SetFontSize(12)
                                .SetFontColor(ColorConstants.BLACK)
                                .SetTextAlignment(TextAlignment.CENTER); // Alinea el contenido al centro

                            doc.Add(logo);

                            // Información de la empresa
                            Paragraph info1 = new Paragraph("Lugar: City Mall")
                                .SetFont(PdfFontFactory.CreateFont(StandardFonts.HELVETICA))
                                .SetFontSize(10)
                                .SetTextAlignment(TextAlignment.CENTER); // Alinea el contenido al centro
                            Paragraph info2 = new Paragraph("Ubicación: Montserrat, Alajuela, Costa Rica")

MvcApplication/Views/Cotizacion/Index.cshtml
<link rel="stylesheet" href="~/Content/CSSEstiloIngresos/EstiloIngresos.css">

@{
    ViewBag.Title = "Cotizar";
}


<section class="section_header">

    <div class="contenidoHeader">
        <div class="izquieroHeader">
            <br />
            <div class="logo">
                <img src="~/Imagenes/Logos/logo1.png" />
            </div>
            <br />
            <h2>
                Cotizaciones
            </h2>

        </div>
        <div class="derechoHeader">
            <img src="~/Imagenes/Visuals/wallpaper13.png" />
        </div>
    </div>
    <div class="wave" style="height: 110px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none"
             style="height: 100%; width: 100%;">
            <path d="M-15.52,87.33 C142.49,-1.47 348.47,137.66 501.97,91.28 L500.00,150.00 L0.00,150.00 Z"
                  style="stroke: none; fill: white;"></path>
        </svg>
    </div>
</section>
<main>
    <center>
        <section class="formulario">
            <center>
                <br />
                <h2 id="titulo">Cotización</h2>
                <br />
                <strong style="font-size:28px; font-family:'Agency FB'" >Seleccione los artículos y podrá ver el costo aproximado que tendría obtenerlos</strong>
                <br />
                <br />
                <div class="enviar">
                    <h5>Para enviar la cotización al correo seleccione el checkbox</h5>
                    @Html.CheckBox("Facturar", new { @id = "facturarCheckBox", @class = "control-label col-md-2", @data_toggle = "modal", @data_target = "#exampleModal" })
                </div>
                <div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group3">
                            </div>
                        </div>
                        <div class="col-md-6">
                        </div>
                    </div>
                </div>
                <br />
                <hr />
                <span class="glyphicons glyphicons-hand-left"></span>
                <div id="resultadoCotizacion">
                    @if (Web.ViewModel.Cotizacion.Instancia.Items.Count() > 0)
                    {
                        @Html.Partial("~/Views/Cotizacion/_PartialViewDetalle.cshtml", (List<Web.ViewModel.ViewModelDetalleIngreso>)ViewBag.DetalleIngreso)
                    }
                    else
                    {
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            El detalle de la cotización no tiene artículos asignados
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }

                </div>
                <hr />
                <section class="abajo">
                    <h5>Seleccione los artículos a cotizar en la sección de abajo</h5>
                </section>
            </center>
        </section>
        <section class="desarrollo">
            <div class="elementos1">
                <div class="elementoizquierdo">
                    <h2 class="titulo">Artículos disponibles</h2>
                </div>
            </div>
            <br />
            <center>
                <div id="ajaxLoader" class="loader" ; style="display:none">
                    <svg viewBox="0 0 80 80">
                        <circle id="test" cx="40" cy="40" r="32"></circle>
                    </svg>
                </div>

                <div id="ajaxLoader" class="loader triangle" ; style="display:none">
                    <svg viewBox="0 0 86 80">
                        <polygon points="43 8 79 72 7 72"></polygon>
                    </svg>
                </div>

                <div id="ajaxLoader" class="loader" ; style="display:none">
                    <svg viewBox="0 0 80 80">
                        <rect x="8" y="8" width="64" height="64"></rect>
                    </svg>
                </div>
                <div class="container">
                    <table class="table">
                        @{
                            List<Infraestructure.Models.Articulo> listaArticulo = ViewBag.listaArticulos;
                        }

                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayName("Nombre")
                                </th>
                                <th>
                                    @Html.DisplayName("Precio")
                                </th>
                                <th>
                                    @Html.DisplayName("Categoría")
                                </th>
                                <th>
                                    @Html.DisplayName("Disponibles")
                                </th>
                                <th>
                                    @Html.DisplayName("Imagen")
                                </th>
                                <th>
                                    @Html.DisplayName("Opciones")
                                </th>
                            </tr>
                        </thead>
                        @foreach (var arti in listaArticulo)
                        {
                            <tbody id="resultado">
                                <tr>
                                    <td>
                                        @arti.nombre
                                    </td>
                                    <td>
                                        ₡@arti.precio.Value.ToString("N")
                                    </td>
                                    <td>
                                        @arti.Categoria.descripcion
                                    </td>
                                    <td>
                                        @arti.stock
                                    </td>
                                    <td>
                                        <img src="data:image/png;base64,@Convert.ToBase64String(arti.imagen)" alt="Imagen de @arti.nombre" width="60" height="60" />
                                    </td>
                                    <td class="columnabotones">
                                        <button class="boton2">@Html.ActionLink("Cotizar", "Cotizar", new { id = arti.id }, new { title = "Agregar a la compra" })</button>
                                    </td>
                                </tr>

                            </tbody>
                        }
                    </table>
                </div>
            </center>
        </section>
    </center>
</main>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 style="color:black;" class="modal-title fs-5" id="exampleModalLabel">Datos para enviar la cotización</h1>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Cerrar"></button>
            </div>

            @using (Html.BeginForm("EnviarCorreo", "Cotizacion"))
            {
                <form>
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="message-text" class="col-form-label">Correo Electrónico:</label>
                            <input name="emailCotizar" class="form-control" id="message-text" style="max-width:100%" placeholder="ejemplo@correo.com">
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button style="background-color:green; color:white" type="submit" class="btn">Aceptar</button>
                    </div>
                </form>
            }

        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryajax")

<script type="text/javascript">

    //Actualizar cantidad de articulos en la comprita
    //Cambio de cantidad en caja de texto
    function updateCantidadC(ctr) {
        var txtCantidad = $(ctr);
        var cantidad = txtCantidad.val();
        var id = txtCantidad.data("productoid");
        $.ajax({
            type: "GET",
            dataType: 'text',
            url: "/Cotizacion/actualizarCantidad",
            data: { "idArticulo": id, "cantidad": cantidad },
            success: function (data) {
                $("#resultadoCotizacion").html('');
                $("#resultadoCotizacion").html(data);
            }, error: function (xhr, status, error) {
                console.log("Error: " + error + ", No Error: " + xhr.status);
            },
        });
    }


    //Actualizar cantidad de articulos que se seteen
    function updateCantLibrosC() {
        $.ajax({
            type: "GET",
            dataType: 'text',
            url: "/Cotizacion/actualizarOrdenCantidad",
            success: function (data) {
                $("#cantidadCompra").html('');
                $("#cantidadCompra").html(data);
            }, error: function (xhr, status, error) {
                console.log("Error: " + error + ", No Error: " + xhr.status);
            },
        });
    }

   
    //Desmarcar el checkbox cuando en el modal le den click en cancelar
    $("button").click(function () {
    // Desmarcar todas las checkboxes
    $("input[type=checkbox]").prop("checked", false);
    })

   </script>
}

MvcApplication/Views/Cotizacion/_PartialViewDetalle.cshtml
@model List<Web.ViewModel.ViewModelDetalleIngreso>

<div class="table-responsive-sm">
    @*Accion, nombre de controlador*@

    <table class="table table-striped">
        @if (Model != null)
        {
            <tr>
                <th>
                    Artículo
                </th>
                <th class="center">
                    Cantidad
                </th>
                <th class="right" style="text-align:right">
                    Precio
                </th>
                <th class="right" style="text-align:right">
                    Total
                </th>
                <th style="text-align:center">
                    Opciones
                </th>
            </tr>

            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(modelItem => item.articulo.id)
                        @Html.DisplayFor(modelItem => item.articulo.nombre)
                    </td>
                    <td class="center" style="width:1.2em">
                        @Html.EditorFor(modelItem => item.cantidad, new { htmlAttributes = new { @class = "form-control changeCantidad", data_productoid = item.articulo.id, onchange = "updateCantidadC(this)" } })
                    </td>
                    <td class="right" style="text-align:right">

                        ₡@Html.DisplayFor(modelItem => item.precio)
                    </td>

                    <td class="right" style="text-align:right">
                        ₡@Html.DisplayFor(modelItem => item.SubTotal)
                    </td>

                    <td style="text-align:center">

                        @Html.ActionLink("X", "eliminarProducto", "Cotizacion", new { id = item.idArticulo }, new { @class = "btn btn-primary" })
                    </td>
                </tr>
            }
        }
    </table>
</div>
@if (Model != null)
{

    <div class="row">
        <div class="col-lg-5 col-sm-5"></div>
        <div class="col-lg-7 col-sm-5 ml-auto">
            <table class="table table-clear">
                <tbody>
                    <tr>
                        <td class="left">
                            <strong>Subtotal</strong>
                        </td>
                        <td class="right" style="width:49%">
                            <strong>₡ @((Web.ViewModel.Cotizacion.Instancia.tirarSubtotal()))</strong>
                        </td>
                    </tr>

                    <tr>
                        <td class="left">
                            <strong>Impuesto de Ventas</strong>
                        </td>
                        <td class="right" style="width:49%">
                            <strong>+ ₡ @((Web.ViewModel.Cotizacion.Instancia.tirarImpuesto()))</strong>
                        </td>
                    </tr>

                    <tr>
                        <td class="left">
                            <strong>Total</strong>
                        </td>
                        <td class="right" style="width:49%">
                            <strong>₡ @((Web.ViewModel.Cotizacion.Instancia.tirarTotal()))</strong>
                        </td>

                    </tr>

                </tbody>
            </table>
            
        </div>
    </div>

    
}