MvcApplication/Controllers/ReparacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using AplicationCore.Services;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Infraestructure.Models;

using System.IO;
using Web.Security;
using MvcApplication.Util;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Kernel.Geom;
using iText.Kernel.Font;
using iText.IO.Font.Constants;
using iText.Kernel.Colors;
using iText.Layout.Element;
using iText.IO.Image;
using iText.Layout.Properties;
using System.Globalization;
using iText.Kernel.Pdf.Canvas.Draw;
using iText.Layout.Borders;

namespace MvcApplication.Controllers
{
    public class ReparacionesController : Controller
    {
        Reportes_Tecnicos re = new Reportes_Tecnicos();
        //Para guardadr la reparacion que se clickee
        int? codigo = 0;
        public static double saldoActual { get; set; }
        //private MyContext db = new MyContext();
        private SelectList listaServicios(long idSer = 0)
        {
            IServiceServicio _ServiceServicio = new ServiceServicio();
            IEnumerable<Servicio_Reparacion> listaServicios = _ServiceServicio.GetServicio();
            return new SelectList(listaServicios, "id", "descripcion", idSer);
        }


        // GET: Reparaciones
   
        public ActionResult Index()
        {
            IEnumerable<Reparaciones> lista = null;
            try
            {
                IServiceReparaciones _ServiceReparaciones = new ServiceReparaciones();
                lista = _ServiceReparaciones.GetReparacion();
                if (TempData["mensaje"] != null)
                    ViewBag.NotificationMessage = TempData["mensaje"].ToString();
            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
            }
            return View(lista);
        }

        public ActionResult IndexUsuario()
        {
            IEnumerable<Reparaciones> lista = null;
            try
            {
                IServiceReparaciones _ServiceReparaciones = new ServiceReparaciones();
                int idUsuario = Convert.ToInt32(TempData["idUser"]);
                lista = _ServiceReparaciones.GetReparacionPorUsuario(idUsuario);
                if (TempData["mensaje"] != null)
                    ViewBag.NotificationMessage = TempData["mensaje"].ToString();
            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
            }
            return View(lista);
        }

        public ActionResult ReportesTecnicosUsuario(int? id)
        {

            IEnumerable<Reportes_Tecnicos> lista = null;
            try
            {
                IServiceRTecnico _ServiceRTecnico = new ServiceRTecnico();
                lista = _ServiceRTecnico.GetReportesByID((long)id);
            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
            }
            return View(lista);
        }

        public ActionResult Save(Reparaciones repa)
        {
        
            IServiceReparaciones _ServiceReparaciones = new ServiceReparaciones();
            ModelState.Remove("imagen");
            if (ModelState.IsValid)
            {
                try
                {
                    repa.usuario_id = Convert.ToInt32(TempData["idUser"]);
                    repa.fecha = DateTime.Now;
                    _ServiceReparaciones.Save(repa);
                    TempData["mensaje"] = Util.SweetAlertHelper.Mensaje("Datos registrados", "reparación guardada con éxito", SweetAlertMessageType.success);
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                    return RedirectToAction("Default", "Error");
                }
            }
           
            return RedirectToAction("Index");
        }

     
        public ActionResult Create()
        {
            ViewBag.ServiciosLista = listaServicios();
            return View();
        }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Edit(int? id)
        {
            IServiceReparaciones _ServiceReparaciones = new ServiceReparaciones();
            Reparaciones repa = null;

            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                repa = _ServiceReparaciones.GetReparacionByID(id.Value);

                if (repa == null)
                {
                    TempData["Message"] = "No existe el proveedor solicitado";
                    TempData["Redirect"] = "Proveedor";
                    TempData["Redirect-Action"] = "Index";
                    // Redireccion a la captura del Error
                    return RedirectToAction("Default", "Error");
                }

                ViewBag.ServiciosLista = listaServicios();
                return View(repa);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Infraestructure.Util.Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Redirect"] = "Rol";
                TempData["Redirect-Action"] = "Index";
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

        }

 
        public ActionResult Details(int? id)
        {
            IServiceReparaciones _ServiceReparaciones = new ServiceReparaciones();
            Reparaciones repa = null;

            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                repa = _ServiceReparaciones.GetReparacionByID(id.Value);

                if (repa == null)
                {
                    return RedirectToAction("Index");
                }
                return View(repa);

            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
                return RedirectToAction("IndexAdmin");
            }
        }

        public ActionResult desabilitar(long id)
        {
            using (MyContext cdt = new MyContext())
            {
                cdt.Configuration.LazyLoadingEnabled = false;

                try
                {
                    Reparaciones art = cdt.Reparaciones.Where(x => x.id == id).FirstOrDefault();
                    art.estado = !art.estado;
                    cdt.Reparaciones.Add(art);
                    cdt.Entry(art).State = EntityState.Modified;
                    cdt.SaveChanges();
                    TempData["mensaje"] = Util.SweetAlertHelper.Mensaje("Reparación eliminada", "Datos eliminados de la base", SweetAlertMessageType.success);
                    return RedirectToAction("Index");

                }
                catch (Exception e)
                {
                    string mensaje = "";
                    Infraestructure.Util.Log.Error(e, System.Reflection.MethodBase.GetCurrentMethod(), ref mensaje);
                    throw;
                }
            }
        }

        public ActionResult buscarReparacionxCedula(string filtro)
        {
            IEnumerable<Reparaciones> lista = null;
            IServiceReparaciones _ServiceReparaciones = new ServiceReparaciones();

            // Error porque viene en blanco 
            if (string.IsNullOrEmpty(filtro))
            {
                lista = _ServiceReparaciones.GetReparacion();
            }
            else
            {
                lista = _ServiceReparaciones.GetReparacionByNombre(filtro);
            }


            // Retorna un Partial View
            return PartialView("_PartialViewVistaxCedula", lista);
        }



        //Reportes Tecnicos--------------------------------------------------
        //-------------------------------------------------------------------
        //-------------------------------------------------------------------

        //VARIABLE QUE LLENA EL CODIGO DEL SERVICIO PARA EL REPORTE

        
        public static int codigoSer { get; set; }
        public ActionResult ReportesTecnicos(int? id)
        {
            this.codigo = id;
            codigoSer = (int)id;

             IEnumerable<Reportes_Tecnicos> lista = null;
            try
            {
                IServiceRTecnico _ServiceRTecnico = new ServiceRTecnico();
                lista = _ServiceRTecnico.GetReportesByID((long)id);
            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
            }
            return View(lista);
        }

        public ActionResult CreateReporte()
        {
            
            return View();
        }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]

        public ActionResult SaveReporte(Reportes_Tecnicos repo)
        {
            MemoryStream target = new MemoryStream();
            IServiceRTecnico _ServiceRTecnico = new ServiceRTecnico();

            ModelState.Remove("id");
            ModelState.Remove("reparacion_id");
            if (ModelState.IsValid)
            {
                try
                {
                    repo.reparacion_id = codigoSer;
                    repo.fecha = DateTime.Now;
                    _ServiceRTecnico.Save(repo);

                    TempData["mensaje"] = Util.SweetAlertHelper.Mensaje("Reporte creado", "La nota se ha registrado en la reparación", SweetAlertMessageType.success);

MvcApplication/Views/Reparaciones/Create.cshtml
@model Infraestructure.Models.Reparaciones
@{
    ViewBag.Title = "Crear Reparación";
}

<link rel="stylesheet" href="~/Content/CSSEstiloReparaciones/EstiloCreate.css">
<section class="section_header">
    <br />
    <div class="contenidoHeader">
        <div class="izquieroHeader">
         
            <div class="logo">
                <img src="~/Imagenes/Logos/logo1.png" />
            </div>
            <br />
            <h2>
                Agregar una nueva reparación
            </h2>

        </div>
        <div class="derechoHeader">
            <img src="~/Imagenes/Visuals/wallpaper12.png" />
        </div>
    </div>
    <div class="wave" style="height: 110px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none"
             style="height: 100%; width: 100%;">
            <path d="M-15.52,87.33 C142.49,-1.47 348.47,137.66 501.97,91.28 L500.00,150.00 L0.00,150.00 Z"
                  style="stroke: none; fill: white;"></path>
        </svg>
    </div>
</section>

<main>
    <center>
        @using (Html.BeginForm("Save", "Reparaciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <h4 id="titulo">Información de la nueva reparación</h4>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="secciones">
                <div class="seccion1">
                    <section class="cuerpoleft">
                        <div class="form-group">
                            @Html.LabelFor(model => model.cliente_id, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.cliente_id, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.cliente_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Servicio_Reparacion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.servicio_reparacion_id, (SelectList)ViewBag.ServiciosLista, "Seleccione acá", new { @class = "combo" })
                                <br />
                                @Html.ValidationMessageFor(model => model.servicio_reparacion_id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.descripcion_articulo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.descripcion_articulo, new { @class = "area" })
                                <br />
                                @Html.ValidationMessageFor(model => model.descripcion_articulo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </section>
                    <section class="cuerporight">

                        <div class="form-group">
                            @Html.LabelFor(model => model.entregaestimada, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.entregaestimada, "{0:yyyy-MM-dd}", new { @class = "form-control datepicker", type = "date" })
                                @Html.ValidationMessageFor(model => model.entregaestimada, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.monto_total, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.monto_total, new { htmlAttributes = new { @class = "form-control", type = "number", step = "0.01" } })
                                @Html.ValidationMessageFor(model => model.monto_total, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.descripcion_problema, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.descripcion_problema, new { @class = "area"})
                                <br />
                                @Html.ValidationMessageFor(model => model.descripcion_problema, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </section>
                    @{
                        string nombre = "Sesión no iniciada";
                        string email = "Perfil";
                        int id = 0;
                        Infraestructure.Models.Usuario oUsuario;
                        //Validar si existe en la sesión
                        if (Session["User"] != null)
                        {
                            oUsuario = (Infraestructure.Models.Usuario)Session["User"];
                            if (oUsuario != null)
                            {
                                nombre = $"{oUsuario.nombre}";
                                email = oUsuario.correo_electronico;
                                id = oUsuario.id;
                                ViewBag.idUser = id;

                                TempData["idUser"] = id;

                            }
                        }
                    }
                </div>
                <div class="seccion2">
                    <div class="form-group2">

                        <input type="submit" value="Guardar Reparación" class="btn" />
                        <button class="btn">@Html.ActionLink("<- Volver Atrás", "Index")</button>
                    </div>
                </div>
                <br />
            </div>
        }
        <br />
        <br />
    </center>
</main>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication/Views/Reparaciones/CreateReporte.cshtml
@model Infraestructure.Models.Reportes_Tecnicos
@{
    ViewBag.Title = "Agregar Reporte";
}

<link rel="stylesheet" href="~/Content/CSSEstiloRTecnicos/EstiloCreate.css">
<section class="section_header">
    <br />
    <div class="contenidoHeader">
        <div class="izquieroHeader">
            <br />
            <div class="logo">
                <img src="~/Imagenes/Logos/logo1.png" />
            </div>
            <br />
            <h2>
                Agregar un nuevo estado
            </h2>

        </div>
        <div class="derechoHeader">
            <img src="~/Imagenes/Visuals/wallpaper12.png" />
        </div>
    </div>
    <div class="wave" style="height: 150px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none"
             style="height: 100%; width: 100%;">
            <path d="M-15.52,87.33 C142.49,-1.47 348.47,137.66 501.97,91.28 L500.00,150.00 L0.00,150.00 Z"
                  style="stroke: none; fill: white;"></path>
        </svg>
    </div>
</section>

<main>
    <center>
        @using (Html.BeginForm("SaveReporte", "Reparaciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <h4 id="titulo">Pasos de la reparación</h4>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="secciones">
                <div class="seccion1">
                    <section class="cuerpoleft">
                        <div class="form-group">
                            @Html.LabelFor(model => model.reporte, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.reporte, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.reporte, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </section>
                    <section class="cuerporight">
                        <div class="form-group">
                            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "datefield", type = "date" } })
                                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </section>
                </div>
                <div class="seccion2">
                    <div class="form-group2">
                        <input type="submit" value="Guardar Reporte" class="btn" title="Guardar el nuevo reporte" />
                        <button class="btn" onclick="goBack()" title="Regresar">Volver Atrás</button>
                    </div>
                </div>
                <br />
            </div>
        }
        <br />
        <br />
    </center>
</main>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
}

MvcApplication/Views/Reparaciones/Edit.cshtml
@model Infraestructure.Models.Reparaciones
@{
    ViewBag.Title = "Editar Reparación";
}

<link rel="stylesheet" href="~/Content/CSSEstiloReparaciones/EstiloCreate.css">
<section class="section_header">
    <br />
    <div class="contenidoHeader">
        <div class="izquieroHeader">
            <br />
            <div class="logo">
                <img src="~/Imagenes/Logos/logo1.png" />
            </div>
            <br />
            <h2>
                Editar una reparación
            </h2>

        </div>
        <div class="derechoHeader">
            <img src="~/Imagenes/Visuals/wallpaper12.png" />
        </div>
    </div>
    <div class="wave" style="height: 150px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none"
             style="height: 100%; width: 100%;">
            <path d="M-15.52,87.33 C142.49,-1.47 348.47,137.66 501.97,91.28 L500.00,150.00 L0.00,150.00 Z"
                  style="stroke: none; fill: white;"></path>
        </svg>
    </div>
</section>

<main>
    <center>
        @using (Html.BeginForm("Save", "Reparaciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <h4 id="titulo">Modificar la reparación</h4>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.id)
            @Html.HiddenFor(model => model.estado)

            <div class="secciones">
                <div class="seccion1">
                    <section class="cuerpoleft">
                        <div class="form-group">
                            @Html.LabelFor(model => model.cliente_id, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.cliente_id, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.cliente_id, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Servicio_Reparacion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">

                                @Html.DropDownListFor(model => model.servicio_reparacion_id, (SelectList)ViewBag.ServiciosLista, "Seleccione acá", new { htmlAttributes = new { @class = "combo" } })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.descripcion_articulo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.descripcion_articulo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.descripcion_articulo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </section>
                    <section class="cuerporight">
                        <div class="form-group">
                            @Html.LabelFor(model => model.entregaestimada, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.entregaestimada, "{0:yyyy-MM-dd}", new { @class = "form-control datepicker", type = "date" })
                                @Html.ValidationMessageFor(model => model.entregaestimada, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.monto_total, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.monto_total, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                @Html.ValidationMessageFor(model => model.monto_total, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.descripcion_problema, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.descripcion_problema, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.descripcion_problema, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </section>
                </div>
                 @{
                    string nombre = "Sesión no iniciada";
                    string email = "Perfil";
                    int id = 0;
                    Infraestructure.Models.Usuario oUsuario;
                    //Validar si existe en la sesión
                    if (Session["User"] != null)
                    {
                        oUsuario = (Infraestructure.Models.Usuario)Session["User"];
                        if (oUsuario != null)
                        {
                            nombre = $"{oUsuario.nombre}";
                            email = oUsuario.correo_electronico;
                            id = oUsuario.id;
                            ViewBag.idUser = id;

                            TempData["idUser"] = id;

                        }
                    }
                }
                <div class="seccion2">
                    <div class="form-group2">

                        <input type="submit" value="Guardar Reparación" class="btn" />
                        <button class="btn">@Html.ActionLink("<- Volver Atrás", "Index")</button>
                    </div>
                </div>
                <br />
            </div>
        }
        <br />
        <br />
    </center>
</main>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication/Views/Reparaciones/IndexCobros.cshtml
@model IEnumerable<Infraestructure.Models.Reparaciones>
@{
    ViewBag.Title = "Cobrar Reparaciones";
}

<link rel="stylesheet" href="~/Content/CSSEstiloNotas/EstiloFrame.css">

<section class="section_header">
    <br />
    <div class="contenidoHeader">
        <div class="izquieroHeader">
            <div class="logo">
                <img src="~/Imagenes/Logos/logo1.png" />
            </div>
            <br />
            <h2>
                Cobrar las reparaciones
            </h2>
        </div>
        <div class="derechoHeader">
            <img src="~/Imagenes/Visuals/wallpaper14.png" />
        </div>
    </div>
    <div class="wave" style="height: 110px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none"
             style="height: 100%; width: 100%;">
            <path d="M-15.52,87.33 C142.49,-1.47 348.47,137.66 501.97,91.28 L500.00,150.00 L0.00,150.00 Z"
                  style="stroke: none; fill: white;"></path>
        </svg>
    </div>
</section>
<main>
    <center>
        <section class="desarrollo">
            <div class="elementos1">
                <div class="elementoizquierdo">
                    <h2 class="titulo">Consulte acá la reparación correspondiente para el pago de la misma</h2>
                </div>
                <div class="col-md-4">
                    <div class="card my-4">
                        <h5 class="card-header">Digíte la cédula del cliente</h5>
                        @using (Ajax.BeginForm("buscarReparacionxID", "Reparaciones", new AjaxOptions
                        {
                            UpdateTargetId = "resultado",
                            InsertionMode = InsertionMode.Replace,
                            HttpMethod = "GET",
                            LoadingElementId = "ajaxLoader"
                        }))
                        {
                            <div class="card-body">
                                <div class="input-group">
                                    @Html.TextBox("filtro", "", new { @class = "form-control", @placeholder = "Digíte...", type = "number", step = "1" })
                                    <button type="submit" class="boton3" title="Buscar Reparación">Buscar</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <br />
            <center>
                <div id="ajaxLoader" class="loader" ; style="display:none">
                    <svg viewBox="0 0 80 80">
                        <circle id="test" cx="40" cy="40" r="32"></circle>
                    </svg>
                </div>

                <div id="ajaxLoader" class="loader triangle" ; style="display:none">
                    <svg viewBox="0 0 86 80">
                        <polygon points="43 8 79 72 7 72"></polygon>
                    </svg>
                </div>

                <div id="ajaxLoader" class="loader" ; style="display:none">
                    <svg viewBox="0 0 80 80">
                        <rect x="8" y="8" width="64" height="64"></rect>
                    </svg>
                </div>
                <div class="container">
                    <table id="resultado" class="table">
                    </table>
                </div>
            </center>
        </section>
    </center>
</main>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryajax")
}
@if (ViewBag.File != null)
{
    <a id="downloadLink" href="@Url.Action("DownloadFile", "Articulo")"></a>

    TempData["file"] = ViewBag.File;

    <script>
        // Utilizar JavaScript para hacer clic en el enlace automáticamente
        document.getElementById("downloadLink").click();
    </script>
}