MvcApplication/Controllers/VentaController.cs
using AplicationCore.Services;
using Infraestructure.Models;
using iText.IO.Font.Constants;
using iText.IO.Image;
using iText.Kernel.Colors;
using iText.Kernel.Font;
using iText.Kernel.Geom;
using iText.Kernel.Pdf;
using iText.Kernel.Pdf.Canvas.Draw;
using iText.Layout;
using iText.Layout.Borders;
using iText.Layout.Element;
using iText.Layout.Properties;
using MvcApplication.Util;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Mail;
using System.Net.Mime;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using Web.Security;

using Web.ViewModel;

namespace MvcApplication.Controllers
{
    public class VentaController: Controller
    {
        IServiceVenta _Serviceventa = new ServiceVenta();
        public static double saldoActual { get; set; }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Index()
        {
            IEnumerable<Venta> lista = null;
            try
            {
                IServiceVenta _ServiceVenta = new ServiceVenta();
                lista = _ServiceVenta.GetVentas();
                if (TempData["mensaje"] != null)
                    ViewBag.NotificationMessage = TempData["mensaje"].ToString();
            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
            }
            return View(lista);
        }

        public ActionResult facturaElectronica(string nombre, string apellidos, string email, string telefono)
        {
            if (nombre.Trim().Length != 0 || apellidos.Trim().Length != 0 || email.Trim().Length != 0 || telefono.Trim().Length != 0)
            {
                TempData["Nombre"]= nombre;
                TempData["Apellidos"] = apellidos;
                TempData["Email"] = email;
                TempData["Telefono"]= telefono;
                TempData["mensaje"] = Util.SweetAlertHelper.Mensaje("Factura generada!", "La factura electrónica se ha creado!", SweetAlertMessageType.success);
              
            }
            else
            {
                TempData["mensaje"] = Util.SweetAlertHelper.Mensaje("Fallo en factura!", "No puede dejar espacios vacíos!", SweetAlertMessageType.error);     
            }
            return RedirectToAction("IndexVenta");

        }
        public JsonResult ActualizarCheckBox(bool isChecked)
        {
            //Actualiza la variable de sesión con el estado actual del CheckBox
            Session["Facturar"] = isChecked;

            //Devuelve el nuevo estado del CheckBox al cliente
            return Json(isChecked, JsonRequestBehavior.AllowGet);
        }
        public static string idForm { get; set; }
        public static string nombreForm { get; set; }
        public static string apellidosForm { get; set; }
        public static string emailForm { get; set; }
        public static string telefonoForm { get; set; }
        public ActionResult obtenerDatosForm()
        {
            //Obtiene los datos del formulario y los guarda en variables
            idForm = Request.Form["id"];
            nombreForm = Request.Form["name"];
            apellidosForm = Request.Form["lastname"];
            emailForm = Request.Form["email"];
            telefonoForm = Request.Form["phone"];

            //Actualiza la variable de sesión con el resultado del formulario
             Session["Facturar"] = true;

            //Redirige al usuario a la página de venta
            return RedirectToAction("IndexVenta");
        }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Save(Venta venta)
        {
            //Mostrar Mensaje de abrir la caja si esta cerrada
            IServiceCajaChica _ServiceCaja = new ServiceCajaChica();
            Arqueos_Caja cajita = new Arqueos_Caja();
            cajita = _ServiceCaja.GetArqueoLast();
            IServiceUsuario serviceUsuario = new ServiceUsuario();
            try
            {
                if (Carrito.Instancia.Items.Count() <= 0)//Valida si hay articulos
                {
                    TempData["mensaje"] = Util.SweetAlertHelper.Mensaje
                           ("Carrito vacío", "No se puede crear una venta sin artículos, por favor verifíque!", SweetAlertMessageType.warning);
                    return RedirectToAction("IndexVenta");
                }
                else
                {
                    if (cajita.estado == false)//Valida si la caja chica esta cerrada
                    {
                        TempData["mensaje"] = Util.SweetAlertHelper.Mensaje
                            ("Problema en Venta", "No se pueden registrar ventas con la caja chica cerrada, por favor verifíque!", SweetAlertMessageType.warning);
                        return RedirectToAction("IndexVenta");
                    }
                    else
                    {
                        Caja_Chica cajaChica = new Caja_Chica();
                        Facturas factura = new Facturas();
                        Usuario user = serviceUsuario.GetUsuarioByID(Convert.ToInt32(TempData["idUser"]));

                        if (Convert.ToString(Request.Form["entrada"]).Trim().Length !=0)//Valida que el ingreso de plata no este vacío
                        {
                            IServiceArticulo serviceArticulo = new ServiceArticulo();

                            Articulo articulo = new Articulo();
                            var listaLinea = Carrito.Instancia.Items;

                            XmlDocument xml = new XmlDocument();
                            XmlNode root = xml.CreateElement("Factura_Electronica");
                            xml.AppendChild(root);

                            //ATRIBUTOS DE FACTURA
                            XmlAttribute xmlns = xml.CreateAttribute("xmlns");
                            xmlns.Value = "https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronica";
                            XmlAttribute xsd = xml.CreateAttribute("xmlns:xsd");
                            xsd.Value = "http://www.w3.org/2001/XMLSchema";
                            XmlAttribute xsi = xml.CreateAttribute("xmlns:xsi");
                            xsi.Value = "http://www.w3.org/2001/XMLSchema-instance";
                            root.Attributes.Append(xmlns);
                            root.Attributes.Append(xsd);
                            root.Attributes.Append(xsi);

                            //CREACION DEL NODO DE INFO DE LA FACTURA ELECTRONICA
                            XmlNode codigoActividad = xml.CreateElement("CodigoActividad");
                            codigoActividad.InnerText = "523601";
                            root.AppendChild(codigoActividad);

                            XmlNode clave = xml.CreateElement("Clave");
                            clave.InnerText = "";
                            root.AppendChild(clave);

                            XmlNode numeroConsecutivo = xml.CreateElement("NumeroConsecutivo");
                            numeroConsecutivo.InnerText = "";
                            root.AppendChild(numeroConsecutivo);

                            XmlNode fechaEmision = xml.CreateElement("FechaEmision");
                            string formatted = DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ssK");
                            fechaEmision.InnerText = formatted;
                            root.AppendChild(fechaEmision);


                            //CREACION DEL NODO DE INFORMACION DE LA EMPRESA
                            XmlNode nodoEmpresa = xml.CreateElement("Emisor");

                            //ASIGNACION DE ELEMENTOS AL NODO DE LA EMPRESA
                            XmlNode nombreEmpresa = xml.CreateElement("Nombre");
                            nombreEmpresa.InnerText = "VYCUZ";

                            XmlNode identificacionEmisor = xml.CreateElement("Identificacion");
                            XmlNode tipo = xml.CreateElement("Tipo");
                            tipo.InnerText = "01";
                            XmlNode numeroIdentificacioEmisor = xml.CreateElement("Numero");
                            numeroIdentificacioEmisor.InnerText = Convert.ToString(200130632);

                            identificacionEmisor.AppendChild(tipo);
                            identificacionEmisor.AppendChild(numeroIdentificacioEmisor);

                            XmlNode nombreComercial = xml.CreateElement("NombreComercial");
                            nombreComercial.InnerText = "VYCUZ";

                            //CREACION DEL NODO DE UBICACION DENTRO DEL NODO DE LA EMRPESA
                            XmlNode nodoUbicacion = xml.CreateElement("Ubicacion");

                            //ASIGNACION DE LOS ELEMENTOS AL NODO DE UBICACION
                            XmlNode provincia = xml.CreateElement("Provincia");
                            provincia.InnerText = "2";
                            XmlNode canton = xml.CreateElement("Canton");
                            canton.InnerText = "01";
                            XmlNode distrito = xml.CreateElement("Distrito");
                            distrito.InnerText = "01";
                            XmlNode otrasSenas = xml.CreateElement("OtrasSenas");
                            otrasSenas.InnerText = "Centro Comercial City Mall segundo piso";

                            //ASGNACION DE LOS ELEMENTOS DENTRO DEL NODO DE UBICACION
                            nodoUbicacion.AppendChild(provincia);
                            nodoUbicacion.AppendChild(canton);
                            nodoUbicacion.AppendChild(distrito);

MvcApplication/Views/Shared/MovimientoCantidad.cshtml
 @{ int cantidadLibros = Web.ViewModel.Carrito.Instancia.GetCountItems();}

<a href="@Url.Action("IndexVenta", "Venta")" class="nav-link">
    Carrito <span class="numero">   @cantidadLibros</span>
</a>

@if (@ViewBag.NotiCarrito != null)
{
    <script>
            @Html.Raw(@ViewBag.NotiCarrito);
    </script>
}

MvcApplication/Views/Shared/ResenaArticulo.cshtml
<button class="agregar" data-bs-toggle="modal" data-bs-target="#exampleModal">Agregar </button>
<br />

MvcApplication/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VYCUZ</title>
    <link rel="shortcut icon" href="~/Imagenes/Logos/logoPestaña.png" type="image/x-icon">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


   
    <link rel="stylesheet" href="~/Content/CSSEstiloLayout/EstiloLayout.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark badge-primary">
        <div class="container-fluid">
            <!--@Html.ActionLink("AFK", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })-->

            <a href="" class="navbar-brand"><img class="imagennav" src="~/Imagenes/Logos/logoIcono.png" alt="Beyond Technology" /></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Inicio", "Index", "Home", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">

                        @Html.ActionLink("Artículos", "IndexCatalogo", "Articulo", new { title = "Ir al catálogo de productos" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Cotizar", "Index", "Cotizacion", new { title = "Ir al formulario de contacto" }, new { @class = "nav-link" })
                    </li>

                    <!--Para el Login VYCUZ-->
                    @{
                        string nombre = "Iniciar Sesión";
                        string email = "Perfil";
                        int id = 0;
                        Infraestructure.Models.Usuario oUsuario;
                        //Validar si existe en la sesión
                        if (Session["User"] != null)
                        {
                            oUsuario = (Infraestructure.Models.Usuario)Session["User"];
                            if (oUsuario != null)
                            {
                                nombre = $"{oUsuario.nombre}";
                                email = oUsuario.correo_electronico;
                                id = oUsuario.id;
                                TempData["idUser"] = id;
                            }
                        }
                    }
                    <li class="nav-item dropdown me-auto" id="login">
                        <a class=" btn btn-success nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">@nombre</a>

                        <div class="dropdown-menu" id="login">
                            @if (Session["User"] != null)
                            {
                                <div class="login">
                                    @* Nombre Usuario *@
                                    Usuario: @nombre
                                </div>
                            }

                            <div class="dropdown-divider"></div>
                            @if (Session["User"] == null)
                            {
                                @Html.ActionLink("Login VYCUZ", "Loguearse", "Home", null, new { @class = "dropdown-item" })
                            }
                            else
                            {

                                @Html.ActionLink("Logout", "Logout", "Home", null, new { @class = "dropdown-item" })
                            }

                        </div>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <div>
        <!--class="container body-content"-->
        @RenderBody()

        <footer>
            <section class="container-fluid sec-footer">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="card desc-box">
                                <div class="card-body">
                                    <div class="card-title">Sobre Nosotros</div>
                                    <div class="card-text">
                                        Somos una empresa con gran auge en ventas de dispositivos electrónicos,
                                        ubicados en el Cuty Mall de Alajuela hemos brindado una excelente atencion a nuestros clientes,
                                        y brindado productos de primera calidad entre ellos: consolas, videojuegos, componentes internos, computadoras, luces, accesorios, etc...
                                        compra con nosotros y viví la experiencia VYCUZ.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card desc-box">
                                <div class="card-body">
                                    <div class="card-title">Contáctenos</div>
                                    <div class="card-text">
                                        <div class="row">
                                            <div class="col">
                                                <img src="~/Imagenes/Iconos/tel.png" alt="Beyond Technology" class="mb-3">
                                                <span>2433-7070</span>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <img src="~/Imagenes/Iconos/ubi.png" alt="Beyond Technology" class="mb-3">
                                                <span>City Mall</span>
                                            </div><!--.col-->
                                        </div><!--.row-->
                                        <div class="row">
                                            <div class="col">
                                                <img src="~/Imagenes/Iconos/mail.png" alt="Beyond Technology" class="mb-3">
                                                <span>VYCUZ@gmail.com</span>
                                            </div><!--.col-->
                                        </div><!--.row-->
                                    </div><!--.card-text-->
                                </div>
                            </div><!--.card-->
                        </div><!--.col-->
                        <div class="col text-center">
                            <br /><br />
                            <img src="~/Imagenes/Logos/logomenu.png" alt="Beyond Technology" class="mb-3">
                            <br class="clearfix">
                            <a href="#" title="Ir al perfil de facebook" class="snip1472"><img src="~/Imagenes/Iconos/facebook.png" alt="Beyond Technology" /></a>
                            <a href="#" title="Ir al perfil de Instagram" class="snip1472"><img src="~/Imagenes/Iconos/instagram.png" alt="Beyond Technology" /></a>
                            <a href="#" title="Ir al chat de Telegram" class="snip1472"><img src="~/Imagenes/Iconos/telegram.png" alt="Beyond Technology" /></a>
                            <a href="#" title="Ir al buscador de Google" class="snip1472"><img src="~/Imagenes/Iconos/google.png" alt="Beyond Technology" /></a>
                        </div><!--.col-->
                    </div><!--.row-->
                </div>
            </section>
        </footer>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/sweetalert")
    @RenderSection("scripts", required: false)



@if (ViewBag.NotificationMessage != null)
{
    <script>
            @Html.Raw(@ViewBag.NotificationMessage);
    </script>
}
</body>
</html>