MvcApplication/Controllers/EmpresaController.cs
using AplicationCore.Services;
using Infraestructure.Models;
using MvcApplication.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Security;


namespace MvcApplication.Controllers
{
    public class EmpresaController : Controller
    {
        // GET: Empresa
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Index()
        {
            IEnumerable<Empresa> lista = null;
            try
            {
                IServiceEmpresa _ServiceEmpresa = new ServiceEmpresa();
                lista = _ServiceEmpresa.GetEmpresa();
                if (TempData["mensaje"] != null)
                    ViewBag.NotificationMessage = TempData["mensaje"].ToString();
            }
            catch (Exception e)
            {
                TempData["Message"] = "Error al procesar los datos! " + e.Message;
            }
            return View(lista);
        }

        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]

        public ActionResult Save(Empresa emp)
        {
      
            IServiceEmpresa _ServiceEmpresa = new ServiceEmpresa();
            if (ModelState.IsValid) {
                try
                {

                    _ServiceEmpresa.Save(emp);
                    TempData["mensaje"] = Util.SweetAlertHelper.Mensaje("Datos registrados", "infomación guardada con éxito", SweetAlertMessageType.success);

                }
                catch (Exception ex)
                {

                    TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                    return RedirectToAction("Default", "Error");
                }
            }
            return RedirectToAction("Index");

        }

        [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult Edit(int? id)
        {
            IServiceEmpresa _ServiceEmpresa = new ServiceEmpresa();
            Empresa emp = null;

            try
            {
                // Si va null
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                emp = _ServiceEmpresa.GetEmpresaByID(id.Value);
                if (emp == null)
                {
                    TempData["Message"] = "No existe la la empresa solicitada";
                    // Redireccion a la captura del Error
                    return RedirectToAction("Default", "Error");
                }
                return View(emp);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Infraestructure.Util.Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }


        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
        public ActionResult Details(int? id)
        {
            IServiceEmpresa _ServiceEmpresa = new ServiceEmpresa();
            Empresa emp = null;

            try
            {
                if (id == null)
                {
                    return RedirectToAction("Index");
                }

                emp = _ServiceEmpresa.GetEmpresaByID(id.Value);

                if (emp == null)
                {
                    return RedirectToAction("Index");
                }
                return View(emp);

            }
            catch (Exception e)
            {
                Infraestructure.Util.Log.Error(e, MethodBase.GetCurrentMethod());
                return RedirectToAction("Index");
            }
        }
    }
}

MvcApplication/Views/Empresa/Details.cshtml
@model Infraestructure.Models.Empresa

@{
    ViewBag.Title = "Detalles";
}

<link rel="stylesheet" href="~/Content/CSSEstiloEmpresa/EstiloDetalleEmpresa.css">

<section class="section_header">
    <br />
    <div class="contenidoHeader">
        <div class="izquieroHeader">
            <br />
            <div class="logo">
                <img src="~/Imagenes/Logos/logo1.png" />
            </div>
            <h2>
                Detalles de la empresa
            </h2>
        </div>
        <div class="derechoHeader">
            <img src="~/Imagenes/Visuals/wallpaper7.png" />
        </div>
    </div>
    <div class="wave" style="height: 110px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none"
             style="height: 100%; width: 100%;">
            <path d="M-15.52,87.33 C142.49,-1.47 348.47,137.66 501.97,91.28 L500.00,150.00 L0.00,150.00 Z"
                  style="stroke: none; fill: white;"></path>
        </svg>
    </div>
</section>
<main>
    <section class="desarrollo">
        <div class="tarjeta">
            <div class="ladoizquierdo">
                <center>
                    <h3>Empresa VYCUZ</h3>
                </center>
                <div class="texto">
                    <p class="">
                        <b>@Html.DisplayNameFor(model => model.nombre):</b> @Html.DisplayFor(model => model.nombre)<br />
                        <b>@Html.DisplayNameFor(model => model.telefono):</b> @Html.DisplayFor(model => model.telefono)<br />
                        <b>@Html.DisplayNameFor(model => model.direccion):</b> @Html.DisplayFor(model => model.direccion)<br />
                    </p>
                </div>
            </div>
            <div class="ladoderecho">
                <center><img alt="Empresa VYCUZ" src="~/Imagenes/Logos/logo1.png" /></center>

            </div>
        </div>
        <br />
        <center>
            <div class="botones">
                <button class="boton1">@Html.ActionLink("Editar datos", "Edit", new { id = Model.id })</button>
                <button class="boton1">@Html.ActionLink("Volver atrás", "Index")</button>
            </div>
        </center>
    </section>
</main>

MvcApplication/Views/Empresa/Edit.cshtml
@model Infraestructure.Models.Empresa

@{
    ViewBag.Title = "Editar Datos";
}

<link rel="stylesheet" href="~/Content/CSSEstiloEmpresa/EstiloCreate.css">

<section class="section_header">
    <br />
    <div class="contenidoHeader">
        <div class="izquieroHeader">
            <br />
            <div class="logo">
                <img src="~/Imagenes/Logos/logo1.png" />
            </div>
            <br />
            <h2>
                Editar datos de la empresa
            </h2>

        </div>
        <div class="derechoHeader">
            <img src="~/Imagenes/Visuals/wallpaper12.png" />
        </div>
    </div>
    <div class="wave" style="height: 150px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none"
             style="height: 100%; width: 100%;">
            <path d="M-15.52,87.33 C142.49,-1.47 348.47,137.66 501.97,91.28 L500.00,150.00 L0.00,150.00 Z"
                  style="stroke: none; fill: white;"></path>
        </svg>
    </div>
</section>

<main>
    <center>
        @using (Html.BeginForm("Save", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <h4 id="titulo">Modificar la información</h4>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)


            <div class="secciones">
                <div class="seccion1">
                    <section class="cuerpoleft">
                        <div class="form-group">
                            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </section>
                    <section class="cuerporight">


                        <div class="form-group">
                            @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </section>
                </div>
                <div class="seccion2">
                    <div class="form-group2">
                        <input type="submit" value="Guardar Datos" class="btn" />
                        <button class="btn">@Html.ActionLink("<- Volver Atrás", "Index")</button>
                    </div>
                </div>
                <br />
            </div>
        }
        <br />
        <br />
    </center>
</main>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication/Views/Empresa/Index.cshtml
@model IEnumerable<Infraestructure.Models.Empresa>

@{
    ViewBag.Title = "Lista empresa";
}


<link rel="stylesheet" href="~/Content/CSSEstiloEmpresa/EstiloListaEmpresa.css">

<section class="section_header">
    <br />
    <div class="contenidoHeader">
        <div class="izquieroHeader">
            <br />
            <br />
            <div class="logo">
                <img src="~/Imagenes/Logos/logo1.png" />
            </div>
            <br />
            <h2>
                Información empresarial
            </h2>

        </div>
        <div class="derechoHeader">
            <img src="~/Imagenes/Visuals/wallpaper6.png" />
        </div>
    </div>
    <div class="wave" style="height: 135px; overflow: hidden;">
        <svg viewBox="0 0 500 150" preserveAspectRatio="none"
             style="height: 100%; width: 100%;">
            <path d="M-15.52,87.33 C142.49,-1.47 348.47,137.66 501.97,91.28 L500.00,150.00 L0.00,150.00 Z"
                  style="stroke: none; fill: white;"></path>
        </svg>
    </div>
</section>
<main>
    <section class="desarrollo">
        <div class="elementos1">
            <h2 class="titulo">Información actual de la empresa</h2>
        </div>
        <br />
        <center>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.direccion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.telefono)
                    </th>
                    <th>
                        Opciones
                    </th>
                </tr>

                @foreach (var item in Model)
                {

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.direccion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.telefono)
                        </td>
                        <td>
                            <button class="boton2">@Html.ActionLink("Editar", "Edit", new { id = item.id }, new { title = "Editar la información" })</button>
                            <button class="boton2">@Html.ActionLink("Detalles", "Details", new { id = item.id }, new { title = "Ver detalles de la empresa" })</button>

                        </td>
                    </tr>
                }

            </table>
        </center>
    </section>
</main>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryajax")
}